

GET http://localhost:2137/stream/scoreboard/score/newGame HTTP/1.1
###

GET http://localhost:5173/stream/scoreboard/score HTTP/1.1
###

GET http://localhost:2137/stream/scoreboard/score/switchsides HTTP/1.1
###

POST http://localhost:2137/stream/scoreboard/score/ HTTP/1.1
content-type: application/json

{
    "playerindex" : 0,
    "score" : 1
}

###

POST http://localhost:2137/stream/scoreboard/score/updateplayername HTTP/1.1
content-type: application/json

{
    "playerIndex" : 1,
    "name" : "skryba TV"
}

###


POST http://localhost:2137/stream/scoreboard/score/visibility HTTP/1.1
content-type: application/json

{
    "visible" : false
}

###


